### ISSUE TITLE
Issues in wiki

### ISSUE THREAD

**Issue by ParimaSA** [Phantawat/ku-polls#53]
- There are no picture of domain model in Domain model page.
- There is no link to Iteration 4 plan on Project Plan page.
- Functional Requirements in Requirements page should be in heading format.

**Comment by Phantawat** [comment]
- Upload picture of domain model in Domain model page.
- Project Plan page is now can navigate to Iteration 4 Plan.
- Reformat of Functional Requirements into heading.
