### ISSUE TITLE
Correct some grammar and format for poll questions

### ISSUE THREAD

**Issue by ParimaSA** [Phantawat/ku-polls#54]
Suggestion: 
- how many ucl that liverpool have won
 -> How many UCL have Liverpool won?
- Which football grass should we go?
 -> Which football field should we go to?
- Will Liverpool buy some player before the transfer window close?
  -> Will Liverpool buy some players before the transfer window closes?

It is entirely optional. I have just used QuillBot to verify the grammar. You can choose to handle it on your own.

**Comment by Phantawat** [comment]
Thank you for your suggestion! I've made the grammar corrections based on your input.
